### ISSUE TITLE
Check it out lol

### ISSUE THREAD

**Issue by icholy** [icholy/poop#1]
@fifteen3 @adam12

**Comment by fifteen3** [comment]
cool. your skills are clearly being wasted by your currently employer. 

I forgot to mention this at  #DevTrx. A friend of mine built a coding challenge for Christmas last year called Advent of Code: http://adventofcode.com/

Check it out you might find it fun.

**Comment by icholy** [comment]
Yeah, I did a couple of those last year. I also like [interview cake](https://www.interviewcake.com/).
